name: Github Package registry
on:
  push:
    branches: master
    tags: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Docker Login
        uses: crazy-max/ghaction-docker-login@v1.1.1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
